trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "My first Azure Pipeline for Maven project"
  displayName: 'Echo Message'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean install'

- script: java -jar target/SimpleMavenApp-1.0-SNAPSHOT.jar
  displayName: 'Run Built JAR'
